In [85]:
import numpy as nm  
import matplotlib.pyplot as mtp 
from sklearn.preprocessing import LabelEncoder
import math
import pandas as pd  
    
le = LabelEncoder()
df= pd.read_csv('computer.csv')  

data_set = df.apply(le.fit_transform) 
x= data_set.iloc[:, :-1].values  
y= data_set.iloc[:, 4].values  
    
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.3)  
  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [86]:
x_train

array([[ 1.01600102,  1.22474487, -1.11803399,  0.89442719],
       [ 1.01600102,  0.        ,  0.89442719,  0.89442719],
       [-0.12700013, -1.22474487, -1.11803399,  0.89442719],
       [-1.27000127, -1.22474487, -1.11803399,  0.89442719],
       [-0.12700013,  1.22474487,  0.89442719, -1.11803399],
       [-1.27000127, -1.22474487,  0.89442719,  0.89442719],
       [ 1.01600102,  1.22474487, -1.11803399, -1.11803399],
       [ 1.01600102,  0.        ,  0.89442719, -1.11803399],
       [-1.27000127,  0.        ,  0.89442719, -1.11803399]])

In [87]:
x_test

array([[-0.12700013,  0.        ,  0.89442719,  0.89442719],
       [ 1.01600102,  1.22474487,  0.89442719,  0.89442719],
       [-0.12700013, -1.22474487, -1.11803399, -1.11803399],
       [-1.27000127,  1.22474487, -1.11803399, -1.11803399],
       [-0.12700013,  1.22474487, -1.11803399,  0.89442719]])

In [88]:
y_train

array([1, 1, 0, 1, 1, 1, 0, 0, 1])

In [89]:
y_test

array([1, 1, 0, 1, 0])

In [90]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=4, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)   

KNeighborsClassifier(n_neighbors=4)

In [91]:
y_pred= classifier.predict(x_test)  

In [92]:
y_pred

array([1, 1, 0, 1, 0])

In [93]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [94]:
cm

array([[2, 0],
       [0, 3]], dtype=int64)

In [95]:
pred = classifier.predict([[0, 2, 1, 1]])
pred

array([1])

In [97]:

if pred[0] == 1:
    print('Prediction is: Yes the student will buy computer')
else:
    print('Prediction is: No the student will not buy computer')

Prediction is: Yes the student will buy computer


In [96]:
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred,labels=[0,1])
print('\nClassification report : \n',matrix)


Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         3

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

