In [34]:
import numpy as nm  
import matplotlib.pyplot as mtp 
from sklearn.preprocessing import LabelEncoder
import math
import pandas as pd  
    
le = LabelEncoder()
df= pd.read_csv('iris.data.csv')  

data_set = df.apply(le.fit_transform) 
x= data_set.iloc[:, :-1].values  
y= data_set.iloc[:, -1].values  
  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25)  
  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [35]:
x_train

array([[-0.58245163,  1.61541599, -1.16795048, -1.30009448],
       [ 0.71048604, -0.06874111,  1.31633449,  1.35589252],
       [ 2.00342371, -1.03111659,  2.00165448,  1.51212705],
       [-1.52276993,  0.17185276, -1.16795048, -1.30009448],
       [-1.52276993,  0.41244664, -1.25361548, -1.30009448],
       [ 1.53326456,  1.37482212,  1.57332949,  1.82459611],
       [ 0.47540646,  0.89363438,  1.14500449,  1.66836158],
       [ 1.06310541, -0.54992885,  0.4596845 ,  0.10601629],
       [-0.58245163,  2.09660373, -1.33928047, -0.98762542],
       [-0.93507099, -1.27171046, -0.82529048, -0.3626873 ],
       [-1.17015057, -1.27171046,  0.20268951,  0.57471988],
       [-1.28769036, -0.06874111, -1.25361548, -1.14385995],
       [-1.28769036, -0.06874111, -1.25361548, -1.45632901],
       [-0.46491184, -1.51230433, -0.48263049, -0.51892183],
       [ 0.47540646, -1.27171046,  0.5453495 ,  0.26225082],
       [ 0.1227871 , -0.79052272,  0.7166795 ,  0.41848535],
       [ 0.71048604, -0.

In [36]:
x_test

array([[ 0.35786668, -0.54992885,  0.4596845 ,  0.73095441],
       [ 0.1227871 , -1.99349207,  0.6310145 ,  0.26225082],
       [ 0.1227871 ,  0.89363438,  0.20268951,  0.41848535],
       [-0.93507099,  1.85600986, -0.91095548, -0.98762542],
       [ 0.47540646,  0.65304051,  0.3740195 ,  0.41848535],
       [-1.40523015,  0.41244664, -1.33928047, -1.30009448],
       [-0.22983226, -0.54992885,  0.20268951, -0.05021824],
       [ 0.24032689, -0.30933498,  0.3740195 ,  0.10601629],
       [-0.93507099,  1.61541599, -1.16795048, -0.98762542],
       [-0.93507099,  1.13422825, -1.25361548, -1.14385995],
       [ 0.59294625,  0.41244664,  0.8880095 ,  1.51212705],
       [ 0.24032689, -0.54992885,  0.3740195 , -0.20645277],
       [-0.11229248, -0.79052272,  0.7166795 ,  0.88718893],
       [ 1.41572477, -0.06874111,  1.40199949,  1.19965799],
       [ 0.47540646, -0.30933498,  1.14500449,  0.73095441],
       [ 0.47540646, -0.54992885,  0.7166795 ,  0.26225082],
       [ 1.65080435, -0.

In [37]:
y_train

array([0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2,
       2, 1, 1, 0, 2, 1, 2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 0, 2, 2, 2, 1, 1,
       0, 1, 1, 1, 0, 2, 0, 0, 1, 2, 2, 1, 1, 2, 2, 0, 0, 1, 2, 2, 1, 1,
       0, 2, 0, 2, 2, 0, 2, 0, 0, 1, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1,
       1, 1])

In [38]:
y_test

array([2, 2, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 2, 2, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 1, 2, 1, 0])

In [39]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=3, metric='minkowski', p=2 )  
classifier.fit(x_train, y_train)   

KNeighborsClassifier(n_neighbors=3)

In [40]:
y_pred= classifier.predict(x_test)  

In [41]:
y_pred

array([2, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 2, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0])

In [42]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [43]:
cm

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  3,  9]], dtype=int64)

In [44]:
from sklearn.metrics import classification_report
matrix = classification_report(y_test,y_pred,labels=[0,1])
print('\nClassification report : \n',matrix)


Classification report : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.79      1.00      0.88        11

   micro avg       0.90      1.00      0.95        26
   macro avg       0.89      1.00      0.94        26
weighted avg       0.91      1.00      0.95        26

